### ISSUE TITLE
How to add GitLab authentication

### ISSUE THREAD

**Issue by ArtuGit** [andock/andock#30]
I perform ` fin andock build deploy`.

On `TASK [andock.build : Update codebase]` I have fatal error:

```
  msg: |-
    Cloning into '/home/andock/andock/projects/ZZZ/XX/XXX-ZZZ__build'...
    fatal: could not read Username for 'https://gitlab.com': No such device or address
  rc: 128
  stderr: |-
```

**Comment by ArtuGit** [comment]
`fin andock environment ssh` gives me `Connection to XXX.YYY.sslip.io closed.`

**Comment by christianwiedemann** [comment]
The andock server has propably no access to gitlab. 
Generate an deploy token at gitlab 
(`https://gitlab.com/USER/PROJECT/settings/repository/deploy_token/create#js-deploy-tokens`)
and add this token to your `andock.yml`

```
git_repository_path: https://TOKEN:PW@gitlab.com/PATH.git
```

`andock environment ssh` works only if the environment is setup was successful

**Comment by ArtuGit** [comment]
@christianwiedemann Thank you
