### ISSUE TITLE
What/where is artifact repository ?

### ISSUE THREAD

**Issue by ArtuGit** [andock/andock#31]
What the difference between `build deploy` and `environment deploy`?

**Comment by christianwiedemann** [comment]
"build deploy" build and push to artifact repro. After that it deploy the last commit from artifact.

Environment deploy just checks out the last commit from artifact repro. This is useful if you build your project on your ci server and push on your own to an artifact repro. (like blt does=

**Comment by ArtuGit** [comment]
What the difference between build and deploy?

`hook_build_tasks` and `hook_update_tasks`?
