### ISSUE TITLE
Andock does not work after Docksal updating

### ISSUE THREAD

**Issue by ArtuGit** [andock/andock#34]
I updated Docksal yesterday to `1.85.1`.

Today Andock does not work.

After `fin init` (a brand new project):

```
user1@desktop:/data/trash/andock-test$ fin addon install andock
Downloading addon hook files...
  andock.pre-install
  andock.post-install
  andock.pre-uninstall
Running pre-install hook...
Downloading addon main script
  andock/andock
Downloading other addon files...
  conf/andock.yml
Running post-install hook...
  Enabling andock ...
Key 'id_rsa' already loaded in the agent. Skipping.
Starting services...
andock-test_db_1 is up-to-date
andock-test_cli_1 is up-to-date
andock-test_web_1 is up-to-date
Creating andock-test_andock_1 ... done
Project URL: http://andock-test.docksal
  andock is enabled successfully.
  Run fin andock to see a list of commands.
Addon andock was installed  
user1@desktop:/data/trash/andock-test$ fin andock 
/bin/bash: andock: command not found
```

**Comment by christianwiedemann** [comment]
I will check that with the new docksal

**Comment by christianwiedemann** [comment]
Thanks for reporting: 
I  will provide an pr to docksal. In the meantime you can fix when you add  `--in=andock`  `.docksal/addons/andock/andock`: line 174.
So the new line should look like:
`fin exec --in=andock gosu docker /bin/bash -c "export ANDOCK_INSIDE_DOCKSAL=true; export ANDOCK_PROJECT_NAME=${ANDOCK_PROJECT_NAME}; $cmd"`

**Comment by christianwiedemann** [comment]
by the way. have you checked https://github.com/andock/boilerplate-drupal8

**Comment by ArtuGit** [comment]
@christianwiedemann 

> by the way. have you checked https://github.com/andock/boilerplate-drupal8

That is great that this exists.

Currently, I work with D7.
