### ISSUE TITLE
Task [andock.build : Stage files] Error

### ISSUE THREAD

**Issue by ArtuGit** [andock/andock#37]
```
  stderr: |-
    rsync: mkdir "/home/andock/andock/projects/...__build/andock-stage" failed: Permission denied (13)
    rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.1]
```

**Comment by christianwiedemann** [comment]
not sure what you are doing or what you mean

**Comment by ArtuGit** [comment]
@christianwiedemann Andock performs this task when I run `fin andock build deploy -v`

**Comment by christianwiedemann** [comment]
andock copy the files into a andock-stage repo. Andock tries to create this folder and this task fails. You can try to `run andock build` clean to delete the build folder and retry. The build folder should not be read only.

**Comment by ArtuGit** [comment]
@christianwiedemann 

I have this error for `fin andock build clean -v`
```
    OSError: [Errno 1] Operation not permitted: '/home/andock/andock/projects/.../.../...__build'
  module_stdout: ''
  msg: MODULE FAILURE
  rc: 1
```
