### ISSUE TITLE
Is it possible to edit Andock standard Ansible tasks?

### ISSUE THREAD

**Issue by ArtuGit** [andock/andock#38]
TASK [andock.server : Create / update Andock user] 
TASK [andock.server : Install Docksal]1
TASK [andock.server : Install andockio/ssh2docksal] 

And others.

**Comment by christianwiedemann** [comment]
yes of course you can create a pr if you like

**Comment by ArtuGit** [comment]
Where are Ansible Tasks in the repo(s)?

**Comment by christianwiedemann** [comment]
Check https://github.com/andock/build/ and https://github.com/andock/environment/
